trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you want to use
  displayName: 'Use Python version'

- script: |
    python hello.py
  displayName: 'Run Hello World script'
